name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.2.3'
      SERVERPOD_PASSWORD_database: 't-W8ujC6OVtAvNuWXv-0UXzp0oS2ElPI'
      SERVERPOD_PASSWORD_redis: 'va1SLqBvzfsDQCRmTOBygSprf5aigr-G'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: legal_lens_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: legal_lens_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: legal_lens_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: legal_lens_server
        run: serverpod generate

      - name: Run tests
        working-directory: legal_lens_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: legal_lens_server
        run: docker compose down -v
