services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: legal_lens
      POSTGRES_PASSWORD: "NOFEs2tFyHbPlOw7JOiF-pLiNbZGCp9w"
    volumes:
      - legal_lens_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "9RYTyTDmrVMy_1frUqXyBNyMJFiZzcOU"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: legal_lens_test
      POSTGRES_PASSWORD: "t-W8ujC6OVtAvNuWXv-0UXzp0oS2ElPI"
    volumes:
      - legal_lens_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "va1SLqBvzfsDQCRmTOBygSprf5aigr-G"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  legal_lens_data:
  legal_lens_test_data:
